### ISSUE TITLE
Node 10.x update

### ISSUE THREAD

**Issue by gregBerthelot** [vividbytes/lambda-edge-image-optimizer#1]
The nodejs6.10 runtime is no longer supported by AWS. Tested with 8.x with success. Tested with latest node 10.x and it does not work. Amazon Linux 2 instances for Lambda no longer contain system utilities, so convert, mogrify and identify from the ImageMagick package are no longer available.

**Comment by nicholasgubbins** [comment]
Hey @gregBerthelot - did you ever work out a solution to the above? Lambda@Edge doesn't support layers so struggling to find a way to deploy a lambda to lambda@edge which is dependent on the image magick binaries

**Comment by gregBerthelot** [comment]
@nicholasgubbins no sorry.

**Comment by mariuskubilius** [comment]
You can use sharp.js instead of imagemagick.

**Comment by gregBerthelot** [comment]
@nicholasgubbins I moved to https://github.com/venveo/serverless-sharp
